### ISSUE TITLE
New logo for footer: JRS Biodiversity Foundation

### ISSUE THREAD

**Issue by kcopas** [gbif/ssg-gbic2#4]
We've received support for GBIC2 from the JRS Biodiversity Foundation. Can you add their logo and an associated link to their website, http://jrsbiodiversity.org ?
![jrs logo large 2013](https://user-images.githubusercontent.com/12379236/41805978-c9944a34-76b3-11e8-8cb3-58fbc60cef61.jpg)

Let me know if you'd like me to produce a reversed-out version in the style of the others.

In the category of 'nice problems to have', do you think the footer's looking a little overloaded in its current format? It strikes me that we might want to reduce the individual sizes a bit so it scales a bit better.

**Comment by thomasstjerne** [comment]
Yes, @kcopas please create a reversed logo ready for use. Thanks /T

**Comment by kcopas** [comment]
Have a PSD of ![this version](https://user-images.githubusercontent.com/12379236/41907047-f2f29ae6-793f-11e8-983b-157db9d4b55d.png) if you need it…
